<a href="https://colab.research.google.com/github/mzengin/randomtests/blob/main/knn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:


class KNN2:
  def __init__(self, k):
    self.k = k
    self.smoothing_value = 1e-8

  def train(self, X, y):
    self.X = X
    self.y = y

  def find_distances(self, X_test):
    distance_vector = np.zeros((X_test.shape[0], self.X.shape[0]))

    for i, x_i in enumerate(X_test):
      #x_i -> 1 X 2
      #X -> m X 2
      distances = np.linalg.norm(X-x_i, axis=1)
      distance_vector[i] = distances
    return distance_vector

  def predict(self, X_test):
    distances = self.find_distances(X_test)
    print(distances)
    distances = np.argsort(distances, axis=1)
    distances = distances[:,0:self.k]
    print(distances)
    y_pred = np.zeros(X_test.shape[0])

    for i, distance in enumerate(distances):
      label = np.argmax(np.bincount(self.y[distance]))
      y_pred[i] = label
    return y_pred

if __name__ == "__main__":
    X = np.random.rand(10,2)
    y = np.random.randint(low=0, high=3, size=10)

    print(X)
    print(y)

    X_test = np.random.rand(2,2)
    y_test = np.random.randint(low=0, high=3, size=2)

    print(X_test)

    KNN = KNN2(k=3)
    KNN.train(X, y)


    labels = KNN.predict(X_test)
    print(labels)



[[0.15192502 0.29709119]
 [0.38023798 0.19269719]
 [0.93850955 0.46513295]
 [0.29475536 0.61202732]
 [0.60859695 0.07955521]
 [0.21340204 0.16974673]
 [0.8750566  0.22791366]
 [0.69871059 0.49296033]
 [0.972046   0.58384149]
 [0.05619617 0.57442289]]
[1 2 0 0 2 1 2 2 1 1]
[[0.55066035 0.9776939 ]
 [0.88870137 0.21721498]]
[[0.78880283 0.80328302 0.64276413 0.44631761 0.90000541 0.8755123
  0.81694757 0.50683873 0.57678902 0.63806139]
 [0.74109351 0.50905416 0.25287186 0.71319608 0.31210366 0.67696559
  0.01733902 0.33486116 0.37598049 0.90590419]]
[[3 7 8]
 [6 2 4]]
[0. 2.]


In [90]:
X = np.random.rand(100,2)


In [91]:
X_test = np.random.rand(3,2)

In [92]:
X_test[0]

array([0.62473466, 0.06847739])

In [96]:
np.linalg.norm(X - X_test[0], axis=1)

array([0.33168666, 0.5254477 , 0.34617828, 0.63355979, 0.53869822,
       0.72349774, 0.94849438, 0.76061267, 0.15531012, 0.7669465 ,
       0.95377863, 0.64085284, 0.56299992, 0.36952217, 0.72444252,
       0.51778381, 0.5194873 , 0.8973982 , 0.65050243, 0.41336191,
       0.24112207, 0.59731607, 0.59830731, 0.80321969, 0.63454223,
       0.73626532, 1.09564967, 0.7192449 , 0.17175483, 0.27475806,
       0.22325062, 0.46293807, 0.37361647, 0.40513407, 0.54841704,
       0.87180499, 0.58239878, 0.71492775, 0.3478064 , 0.88915298,
       0.93632514, 0.78136016, 0.37758166, 0.36714719, 0.9369299 ,
       0.47913677, 0.86747966, 0.26072124, 0.34241815, 0.96436319,
       0.20371933, 0.94164902, 0.37098869, 0.59120058, 0.70540331,
       0.81257999, 0.48774481, 0.22403749, 0.5743541 , 0.23309816,
       0.47850629, 0.57307759, 0.3623477 , 0.81913175, 0.32086021,
       0.68212888, 0.40896154, 0.37630068, 0.40403836, 0.24665049,
       0.59649449, 0.22526366, 0.62164776, 0.34372615, 0.91772

In [103]:
X

array([[0.63893144, 0.56990783],
       [0.60173653, 0.76229022],
       [0.39330505, 0.13008448],
       [0.37013108, 0.28527901],
       [0.59194967, 0.08286027]])

In [104]:
X[:,0:1]

array([[0.63893144],
       [0.60173653],
       [0.39330505],
       [0.37013108],
       [0.59194967]])

In [79]:
#random.randint(low, high=None, size=None, dtype=int)
y = np.random.randint(low=0, high=4, size=100)

In [80]:
y

array([1, 2, 3, 3, 2, 1, 0, 0, 3, 2, 0, 3, 1, 0, 3, 3, 2, 3, 1, 0, 0, 3,
       0, 3, 2, 1, 1, 0, 1, 3, 0, 3, 0, 3, 1, 2, 2, 2, 2, 2, 1, 3, 3, 2,
       0, 2, 2, 1, 2, 3, 1, 0, 1, 3, 1, 3, 2, 2, 2, 0, 2, 1, 3, 0, 3, 0,
       1, 0, 1, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 0, 0, 0, 3, 3, 0, 3, 1, 1,
       3, 3, 3, 2, 1, 1, 0, 1, 1, 0, 0, 0])

In [89]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
array = np.array([1,2,1, 1])

bincount = np.bincount(array)

In [111]:
bincount

array([0, 3, 1])

In [112]:
np.zeros(5)

array([0., 0., 0., 0., 0.])